from typing import NamedTuple, Annotated
import numpy as np
import bpy
from procfunc.nodes import types as t
from procfunc.nodes.types import ProcNode, SocketOrVal
import procfunc as pf


@pf.nodes.node_function
def simple_chair(
    grid_vertices: t.SocketOrVal[int],
    back_height: t.SocketOrVal[float],
    seat_thickness: t.SocketOrVal[float],
    leg_length: t.SocketOrVal[float],
) -> pf.ProcNode: 
    # Code generated by procfunc v0.22.0
    grid = pf.nodes.geo.mesh_grid(vertices_x=grid_vertices, vertices_y=grid_vertices)
    
    input_index = pf.nodes.geo.input_index()
    
    extrude_b_0 = grid_vertices.astype(dtype=float) - 1.0
    
    extrude_for_back_selection = pf.nodes.func.less_than(a=input_index, b=extrude_b_0.astype(dtype=int))
    extrude_for_back = pf.nodes.geo.extrude_mesh(
        mesh=grid.mesh,
        selection=extrude_for_back_selection,
        offset_scale=seat_thickness + back_height,
        individual=False,
    )
    input_face_neighbors = pf.nodes.geo.input_mesh_face_neighbors()
    
    is_corner = pf.nodes.func.equal(a=input_face_neighbors.face_count, b=2)
    
    extrude_for_legs = pf.nodes.geo.extrude_mesh(
        mesh=grid.mesh,
        selection=is_corner,
        offset_scale=leg_length * -1.0,
        individual=False,
    )
    
    flip_faces = pf.nodes.geo.flip_faces(extrude_for_legs.mesh)
    
    extrude_for_seat_thickness = pf.nodes.geo.extrude_mesh(
        mesh=grid.mesh,
        offset_scale=seat_thickness,
        individual=False,
    )
    
    extruded_with_top = pf.nodes.geo.join_geometry(
        [extrude_for_back.mesh, flip_faces, grid.mesh, extrude_for_seat_thickness.mesh]
    )
    
    return extruded_with_top

if __name__ == '__main__':
    # Code generated by procfunc v0.22.0
    simple_chair_result = simple_chair()
    
